/**
 *  \file
 *  \remark This file is part of ULTRA.
 *
 *  \copyright Copyright (C) 2024 EOS di Manlio Morini.
 *
 *  \license
 *  This Source Code Form is subject to the terms of the Mozilla Public
 *  License, v. 2.0. If a copy of the MPL was not distributed with this file,
 *  You can obtain one at http://mozilla.org/MPL/2.0/
 */

#if !defined(ULTRA_HASH_T_H)
#define      ULTRA_HASH_T_H

#include <array>
#include <bit>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <span>

namespace ultra
{
///
/// A 128bit unsigned integer used as individual's signature / hash table
/// look-up key.
///
struct hash_t
{
  explicit hash_t(std::uint64_t a = 0, std::uint64_t b = 0) : data{a, b} {}

  /// Resets the content of the object.
  void clear() noexcept { data[0] = data[1] = 0; }

  /// Standard equality operator for hash signature.
  [[nodiscard]] bool operator==(const hash_t &) const noexcept = default;

  [[nodiscard]] bool operator<(const hash_t &rhs) const noexcept
  {
    return data[0] < rhs.data[0]
           || (data[0] == rhs.data[0] && data[1] < rhs.data[1]);
  }

  /// Used to combine multiple hashes.
  ///
  /// \note
  /// In spite of its handy bit-mixing properties, XOR is not a good way to
  /// combine hashes due to its commutativity (e.g. see
  /// https://stackoverflow.com/q/5889238/3235496).
  void combine(hash_t h) noexcept
  {
    // This is the simple algorithm used in `Apache.Commons.HashCodeBuilder`.
    // It uses simple prime number multiplication and is a special case of
    // Bob Jenkins' idea (`m * H(A) + H(B)`).
    data[0] = data[0] * 37 + h.data[0];
    data[1] = data[1] * 37 + h.data[1];

    // An alternative from Boost is:
    //data[0] ^= h.data[0] + 0x9e3779b9 + (data[0] << 6) + (data[0] >> 2);
    //data[1] ^= h.data[1] + 0x9e3779b9 + (data[1] << 6) + (data[1] >> 2);
  }

  /// We assume that a string of 128 zero bits means empty.
  [[nodiscard]] bool empty() const noexcept { return !data[0] && !data[1]; }

  // Serialization.
  bool load(std::istream &);
  bool save(std::ostream &) const;

  // Data members.
  std::uint_least64_t data[2];
};

std::ostream &operator<<(std::ostream &, hash_t);

// Implementation details for MurmurHash3 x64 128-bit hashing.
// This namespace contains the low-level primitives shared by both the
// one-shot (`murmurhash3::hash128`) and incremental (`murmurhash3_sink`)
// implementations: block mixing, tail processing, finalisation.
// Keeping these routines in a single place guarantees bitwise equivalence
// between hashing modes and avoids code duplication.
namespace internal
{

static constexpr std::uint64_t c1 {0x87c37b91114253d5};
static constexpr std::uint64_t c2 {0x4cf5ad432745937f};

inline std::uint64_t fmix(std::uint64_t k) noexcept
{
  // The constants were generated by a simple simulated-annealing algorithm.
  k ^= k >> 33;
  k *= 0xff51afd7ed558ccd;
  k ^= k >> 33;
  k *= 0xc4ceb9fe1a85ec53;
  k ^= k >> 33;

  return k;
}

inline std::uint32_t fmix(std::uint32_t k) noexcept
{
  // The constants were generated by a simple simulated-annealing algorithm.
  k ^= k >> 16;
  k *= 0x85ebca6b;
  k ^= k >> 13;
  k *= 0xc2b2ae35;
  k ^= k >> 16;

  return k;
}

///
/// Finalises the hash state after all input has been processed.
///
/// \param[in,out] h         current hash state
/// \param[in]     total_len total length of the input, in bytes
///
/// This step incorporates the message length and applies the final avalanche
/// mixing to produce the final 128-bit hash value.
///
inline void finalize(hash_t &h, std::size_t total_len) noexcept
{
  h.data[0] ^= total_len;
  h.data[1] ^= total_len;

  h.data[0] += h.data[1];
  h.data[1] += h.data[0];

  h.data[0] = fmix(h.data[0]);
  h.data[1] = fmix(h.data[1]);

  h.data[0] += h.data[1];
  h.data[1] += h.data[0];
}

///
/// Mixes a single 128-bit block into the hash state.
///
/// \param[in,out] h  current hash state
/// \param[in]     k1 first 64-bit block
/// \param[in]     k2 second 64-bit block
///
/// This function corresponds to the body mixing step of the MurmurHash3
/// x64 128-bit algorithm.
///
inline void process_block(hash_t &h, std::uint64_t k1,
                          std::uint64_t k2) noexcept
{
  k1 *= c1;
  k1  = std::rotl(k1, 31);
  k1 *= c2;
  h.data[0] ^= k1;

  h.data[0] = std::rotl(h.data[0], 27);
  h.data[0] += h.data[1];
  h.data[0] = h.data[0] * 5 + 0x52dce729;

  k2 *= c2;
  k2  = std::rotl(k2, 33);
  k2 *= c1;
  h.data[1] ^= k2;

  h.data[1] = std::rotl(h.data[1], 31);
  h.data[1] += h.data[0];
  h.data[1] = h.data[1] * 5 + 0x38495ab5;
}

///
/// Processes the remaining tail bytes (0–15) of the input.
///
/// \param[in,out] h    current hash state
/// \param[in]     tail pointer to the remaining bytes
/// \param[in]     len  number of valid bytes in `tail`
///
/// This implements the exact tail-handling logic defined by the MurmurHash3
/// x64 128-bit reference implementation.
///
inline void process_tail(hash_t &h,
                         const std::byte *tail, std::size_t len) noexcept
{
  std::uint64_t k1(0), k2(0);

  switch (len)
  {
  case 15: k2 ^= std::uint64_t(tail[14]) << 48;  [[fallthrough]];
  case 14: k2 ^= std::uint64_t(tail[13]) << 40;  [[fallthrough]];
  case 13: k2 ^= std::uint64_t(tail[12]) << 32;  [[fallthrough]];
  case 12: k2 ^= std::uint64_t(tail[11]) << 24;  [[fallthrough]];
  case 11: k2 ^= std::uint64_t(tail[10]) << 16;  [[fallthrough]];
  case 10: k2 ^= std::uint64_t(tail[ 9]) <<  8;  [[fallthrough]];
  case  9: k2 ^= std::uint64_t(tail[ 8]);
           k2 *= c2; k2 = std::rotl(k2, 33); k2 *= c1; h.data[1] ^= k2;
           [[fallthrough]];
  case  8: k1 ^= std::uint64_t(tail[ 7]) << 56;  [[fallthrough]];
  case  7: k1 ^= std::uint64_t(tail[ 6]) << 48;  [[fallthrough]];
  case  6: k1 ^= std::uint64_t(tail[ 5]) << 40;  [[fallthrough]];
  case  5: k1 ^= std::uint64_t(tail[ 4]) << 32;  [[fallthrough]];
  case  4: k1 ^= std::uint64_t(tail[ 3]) << 24;  [[fallthrough]];
  case  3: k1 ^= std::uint64_t(tail[ 2]) << 16;  [[fallthrough]];
  case  2: k1 ^= std::uint64_t(tail[ 1]) <<  8;  [[fallthrough]];
  case  1: k1 ^= std::uint64_t(tail[ 0]);
           k1 *= c1; k1 = std::rotl(k1, 31); k1 *= c2;
           h.data[0] ^= k1;
  }
}

}  // namespace internal

///
/// MurmurHash3 (https://github.com/aappleby/smhasher) by Austin Appleby.
///
/// MurmurHash3 is a relatively simple non-cryptographic hash algorithm. It's
/// noted for being fast, with excellent distribution, avalanche behavior and
/// overall collision resistance.
///
/// \note
/// An interesting alternative is SpookyHash
/// (https://burtleburtle.net/bob/hash/spooky.html) by Bob Jenkins.
///
class murmurhash3
{
public:
  [[nodiscard]] static hash_t hash128(const void *const, std::size_t,
                                      std::uint32_t = 1973) noexcept;

private:
  template<std::integral T> [[nodiscard]] static T get_block(
    const T *, std::size_t) noexcept;
};

///
/// Hashes a single message in one call, return 128-bit output.
///
/// \param[in] data data stream to be hashed
/// \param[in] len  length, in bytes, of `data`
/// \param[in] seed initialization seed
/// \return         the signature of `data`
///
inline hash_t murmurhash3::hash128(const void *const data, std::size_t len,
                                   std::uint32_t seed) noexcept
{
  const auto n_blocks(len / 16);  // block size is 128bit

  // Body.
  const auto *blocks(reinterpret_cast<const std::uint64_t *>(data));
  hash_t h(seed, seed);

  for (std::size_t i(0); i < n_blocks; ++i)
  {
    std::uint64_t k1(get_block(blocks, i * 2 + 0));
    std::uint64_t k2(get_block(blocks, i * 2 + 1));

    internal::process_block(h, k1, k2);
  }

  // Tail.
  internal::process_tail(
    h,
    reinterpret_cast<const std::byte *>(data) + n_blocks * 16, len & 15);

  internal::finalize(h, len);

  return h;
}

template<std::integral T>
inline T murmurhash3::get_block(const T *p, std::size_t i) noexcept
{
  // The reason we do a memcpy() instead of simply returning `p[i]` is because
  // doing it this way avoids violations of the strict aliasing rule.

  T tmp;
  std::memcpy(&tmp, p + i, sizeof(T));
  return tmp;
}

///
/// Incremental MurmurHash3 x64 128-bit sink.
///
/// This class allows hashing a byte stream incrementally, producing a 128-bit
/// MurmurHash3 signature equivalent to hashing the entire input in a single
/// call to `murmurhash3::hash128`.
///
/// It's designed to act as a *byte sink* for streaming algorithms such as
/// `gp::individual::pack`, avoiding temporary buffers and repeated hashing.
///
class murmurhash3_sink
{
public:
  explicit murmurhash3_sink(std::uint32_t = 1973) noexcept;

  void write(std::span<const std::byte>) noexcept;
  [[nodiscard]] hash_t final() noexcept;

private:
  void process_block(const std::byte* data) noexcept;

private:
  hash_t h_;
  std::array<std::byte, 16> tail_ {};
  std::size_t tail_size_ {0};
  std::size_t total_len_ {0};
};  // class murmurhash3_sink

///
/// Constructs a new incremental MurmurHash3 sink.
///
/// \param[in] seed initial seed value (default: 1973)
///
inline murmurhash3_sink::murmurhash3_sink(std::uint32_t seed) noexcept
  : h_(seed, seed)
{
}

///
/// Feeds a sequence of bytes into the hash state.
///
/// \param[in] bytes byte span to be hashed
///
/// This function may be called multiple times with arbitrary chunk sizes.
/// The resulting hash is identical to hashing the concatenation of all
/// provided byte sequences in a single call.
///
inline void murmurhash3_sink::write(std::span<const std::byte> bytes) noexcept
{
  total_len_ += bytes.size();

  // Fill tail if needed.
  if (tail_size_)
  {
    const auto n(std::min<std::size_t>(16 - tail_size_, bytes.size()));

    std::memcpy(tail_.data() + tail_size_, bytes.data(), n);
    tail_size_ += n;
    bytes = bytes.subspan(n);

    if (tail_size_ == 16)
    {
      process_block(tail_.data());
      tail_size_ = 0;
    }
  }

  // Process full blocks.
  while (bytes.size() >= 16)
  {
    process_block(bytes.data());
    bytes = bytes.subspan(16);
  }

  // Store remaining bytes as tail.
  if (!bytes.empty())
  {
    std::memcpy(tail_.data(), bytes.data(), bytes.size());
    tail_size_ = bytes.size();
  }
}

inline void murmurhash3_sink::process_block(const std::byte *data) noexcept
{
  std::uint64_t k1, k2;
  std::memcpy(&k1, data +          0, sizeof(k1));
  std::memcpy(&k2, data + sizeof(k1), sizeof(k2));

  internal::process_block(h_, k1, k2);
}

///
/// Finalises the hash computation and returns the resulting signature.
///
/// \return the 128-bit MurmurHash3 value corresponding to the input stream
///
/// \warning
/// Calling this function finalises the internal state. Further calls to
/// `write()` result in undefined behaviour.
///
inline hash_t murmurhash3_sink::final() noexcept
{
  internal::process_tail(h_, reinterpret_cast<const std::byte *>(tail_.data()),
                         tail_size_);
  internal::finalize(h_, total_len_);
  return h_;
}

using hash = murmurhash3;
using hash_sink = murmurhash3_sink;

///
/// \param[in] t a value belonging to a fundamental types
/// \return      the value content viewed as a raw sequence of bytes
///
template <class T>
requires (std::integral<T> || std::floating_point<T>)
[[nodiscard]] std::span<const std::byte, sizeof(T)> bytes_view(const T &t)
{
  return std::span<const std::byte, sizeof(T)>{
    reinterpret_cast<const std::byte *>(std::addressof(t)), sizeof(T)};
}

[[nodiscard]] std::span<const std::byte> bytes_view(const std::string &);

}  // namespace ultra

#endif  // include guard
